alias bc='bc -l'
alias dfp='df -lhP|column -t'
alias dusort='sudo du -sh * | sort -h'
alias git='hub'
alias hibernation='sudo systemctl hibernate'
alias ip='ip -o -c'
alias la='ls -ltrah --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mtm='tmux -2u a || tmux -2u'
alias pr='pipenv run'
alias prp='pipenv run python'
alias suspension='sudo systemctl suspend'
alias tmux='tmux -2u'
alias vi='nvim'
alias vim='nvim'
alias xup='xrdb ~/.Xresources'
alias yaya='yay -Suy --noconfirm'
